---
AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'test/**/*'
    - 'bin/**'
    - 'vendor/**/*'
Style/AlignHash:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FileName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/StringLiterals:
  Enabled: false
